default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary
    <<: *default
    database: mat_vulcan_development
    pool: 5
    timeout: 5000
  queue:
    <<: *primary
    database: mat_vulcan_queue_development
    migrations_paths: db/queue_migrate

test:
  primary: &test
    <<: *default
    database: mat_vulcan_test
    pool: 5
    timeout: 5000
  queue:
    <<: *test
    database: mat_vulcan_queue_test
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: mat_vulcan_production
    username: mat_vulcan
    pool: 5
    timeout: 5000
    password: <%= ENV["MAT_VULCAN_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mat_vulcan_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mat_vulcan_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mat_vulcan_production_cable
    migrations_paths: db/cable_migrate